--- 
title: "The Scientific Publishing Toolbox"
author: "John J. Curtin, Ph.D."
institute: "University of Wisconsin-Madison"
format: 
  revealjs:
    scrollable: true
    css: slides.css
    slide-number: true
    show-slide-number: all 
--- 

# Overview

Today is an informal guided tour of the tools and systems used for scientific publishing broadly

- Quarto Publishing System
- R Markdown
- R and the Tidyverse
- Git and Github

- Provide some instruction but good docs are available at
  - [Quarto](https://quarto.org/) 
  - [Github Support](https://support.github.com/)
  - [Git](https://git-scm.com/docs)
  - [Tidyverse.org](https://www.tidyverse.org/)


# Evolution of the Quarto Publishing System 

1. The R script (.R) - see [example 1](1_r.r)
2. R Markdown (.Rmd)
  - An implementation of Markdown for R to implement notebooks
  - Similar to Jupyter notebooks but in plain text vs. json (better for version control)
  - Only used for publishing reports/notebooks in html, pdf, etc
  - Other packages/systems were needed for books, slides, manuscripts, etc
3. Enter Quarto Publishing System


# Quarto Publishing System

Quarto is an open-source scientific and technical publishing system

- Can publish numerous products
  - Reports in html, pdf, or other formats
  - Manuscripts as html, pdf, or word
  - Slide decks - locally or on web
  - Books on web
  - Websites

- Can reuse the same code for these products
- Products update as data or analysis decisions are updated
- Provides for transparency (code and output can be combined)  
- Text based system works will with version control


# The Quarto Document

The building block of Quarto is the document file (.qmd)

It is similar to a Jupyter notebook  

- Can be used interactively
- Can be rendered to reports
- Combines code, output and commentary
- Better for version control than Jupyter notbooks?

# Components of a Quart Document

It has three types of content

- A YAML header at top 
- Code chunks
- Markdown text

Lets look at a [simple example 2](2_qmd.qmd)


# Rendering a Quarto Document

Quarto documents are rendered using the `quarto render` command

- Can be rendered to html, pdf, or other formats
- Can render using RStudio button but more control using command line in terminal
  - `quarto render 2_quarto.qmd --to pdf` 
  - `quarto render 2_quarto.qmd --to html`
  
# Format Control in YAML

We can control the format of the output in the YAML header (see [example 3](3_quarto.qmd)) 

- Indicated that we will include a table of contents with depth = 2
- Indicated that the html file will render to a single file (preferred for sharing)

- Lets render it
  - will default to the format listed
  - `quarto render 3_quarto.qmd`
- Can still render to other formats via terminal
  - `quarto render 3_quarto.qmd --to pdf`
  
  
# Multiple Formats

- Can include multiple formats in the YAML header
- See [example 4](4_quarto.qmd)
- Can render in various ways
  - `quarto render 3_quarto.qmd --to html`
  - `quarto render 3_quarto.qmd --to pdf`
  - `quarto render 4_quarto.qmd --to all`

# Publishing Quarto Documents

HTML rendered Quarto documents can be published to the web

- Various options
  - [QuartoPub](https://quartopub.com/) is a free hosting service that is suitable for public reports
  - Exploring Posit Connect for private reports (not free)

- Best done from the command line
  - `quarto publish quarto-pub 3_quarto.qmd`
  - Follow instructions
  - May need to log in to QuartoPub and allow access
  - Public info (no account credentials) about the published document will be saved in `_publish.yml` on first publication
  - Rendered locally first but don't need local files.  I prefer to delete them by publishing with a bash shell script (see [publish.sh](publish.sh))


# Publishing Slide Decks with Quarto

Can publish the same notebooks as slide decks

- Various formats available
- revealjs is our choice
- Can be published local or to QuartoPub or other hosting services (QuartoPub preferred)
- Just need to change/add format in YAML header for revealjs
- see [example 5](5_quarto.qmd)

# My Slide Decks 

You can see my slide decks for presentations from the last year at [https://github.com/jjcurtin/slide_decks](https://github.com/jjcurtin/slide_decks) 

- NB: This is set up as a manuscript project (more on that in a moment) so the structure is a bit more complicated
- The slide decks are in the `_presentations` folder
- This slide deck (and sample documents) is in `_presentations/2024/quarto_dshb`
- We can clone this repo in a bit...

# Moving Beyond the Quarto Document

Quarto can also be used to publish more complex products

- Manuscripts
- Books
- Websites

These require some additional setup files but still very straight forward

Two Examples

- [Manuscript](https://jjcurtin.github.io/study_match/)
- [Book](https://jjcurtin.github.io/book_glm/)


We use Github as repository and host for these products

# Git

What is git and why do we use it?

- distributed version control system
- no need for _1, _2 _2024-01-1
- safe (for students use; for disasters)
- easy to track changes
- easy to share with others
- meant primarily for text (not binary; not data) 


# Github

- Host remote (vs. local) repo
- Pull down from remote when starting work
- Push up to remote when done working
- Free (for most features)
- Most well known hosting service (gitlab, sourceforge)
- Used to distribute code for apps, materials from books/course, code from studies

- Can also be used to easily "publish" and maintain products (manuscripts, books, websites) when combined with a publishing system like Quarto

# Github for Websites

Github repos can be configured to display a website

  - This website can be authored and published using Quarto (and R)
  - Can use these web pages for course materials and open source books
  - Study manuscript and notebooks
  - your personal website/portfolio of products
  
These website are accessed at:

  - username.github.io/repo_name

# My Github

I have public repos for

- courses I teach
- every study we publish (code and now papers, analysis notebooks, not data)
- generic code we share: [https://github.com/jjcurtin/lab_support](https://github.com/jjcurtin/lab_support)
- slide decks

# Gaylen Fronk's Dissertation Manuscript

We can clone Gaylen's Quarto manuscript project to see how it is set up

- URL is standardized:  github.com/username/repo_name
- [https://github.com/jjcurtin/study_match](https://github.com/jjcurtin/study_match)
- Can get clone URL directly from Github
- `git clone git@github.com:jjcurtin/study_match.git`

- Lets look at it!

# 610 book

610 course materials are available in my github repo: 

- [https://github.com/jjcurtin/book_glm](https://github.com/jjcurtin/book_glm)
- `git clone git@github.com:jjcurtin/book_glm.git`

- Lets look at it
- You can edit the slide decks for each unit!
- You can render/publish your own version of the slides locally or on QuartoPub